// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFG1DGqnITna9XtWRDpJE7h-D0Fs37zC0',
    appId: '1:584376772611:web:c8bd0a1686102566f4c636',
    messagingSenderId: '584376772611',
    projectId: 'bisuchat-1',
    authDomain: 'bisuchat-1.firebaseapp.com',
    storageBucket: 'bisuchat-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOCdg2EUzPcMKPOeTzpEUpJPul25LPsY',
    appId: '1:584376772611:android:bf2636311d1382f3f4c636',
    messagingSenderId: '584376772611',
    projectId: 'bisuchat-1',
    storageBucket: 'bisuchat-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-ZYwXIP1iIkMnmXJAmHitBw1NatKnkQ',
    appId: '1:584376772611:ios:0438dd6ad797caf5f4c636',
    messagingSenderId: '584376772611',
    projectId: 'bisuchat-1',
    storageBucket: 'bisuchat-1.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-ZYwXIP1iIkMnmXJAmHitBw1NatKnkQ',
    appId: '1:584376772611:ios:0438dd6ad797caf5f4c636',
    messagingSenderId: '584376772611',
    projectId: 'bisuchat-1',
    storageBucket: 'bisuchat-1.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFG1DGqnITna9XtWRDpJE7h-D0Fs37zC0',
    appId: '1:584376772611:web:de6b555c99a83034f4c636',
    messagingSenderId: '584376772611',
    projectId: 'bisuchat-1',
    authDomain: 'bisuchat-1.firebaseapp.com',
    storageBucket: 'bisuchat-1.firebasestorage.app',
  );
}
