// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDV6f5YOQOVAl045P4SJb8uoJAOROK5o',
    appId: '1:82105313297:web:7024b2e912c0e67d0d29b0',
    messagingSenderId: '82105313297',
    projectId: 'chatapp-im155u',
    authDomain: 'chatapp-im155u.firebaseapp.com',
    storageBucket: 'chatapp-im155u.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAZVUiT5Uv0V80cDg1AHpR2svzvMZ3is',
    appId: '1:82105313297:android:d727ca4eb93e672e0d29b0',
    messagingSenderId: '82105313297',
    projectId: 'chatapp-im155u',
    storageBucket: 'chatapp-im155u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8b6e1tbtI2VDrm250n020BEG2RwwNeM',
    appId: '1:82105313297:ios:b36b9e74c37dbca30d29b0',
    messagingSenderId: '82105313297',
    projectId: 'chatapp-im155u',
    storageBucket: 'chatapp-im155u.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8b6e1tbtI2VDrm250n020BEG2RwwNeM',
    appId: '1:82105313297:ios:b36b9e74c37dbca30d29b0',
    messagingSenderId: '82105313297',
    projectId: 'chatapp-im155u',
    storageBucket: 'chatapp-im155u.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGDV6f5YOQOVAl045P4SJb8uoJAOROK5o',
    appId: '1:82105313297:web:81b4d1cefd9b24f70d29b0',
    messagingSenderId: '82105313297',
    projectId: 'chatapp-im155u',
    authDomain: 'chatapp-im155u.firebaseapp.com',
    storageBucket: 'chatapp-im155u.firebasestorage.app',
  );
}
